<a href="https://colab.research.google.com/github/m-ony/mineria-de-datos/blob/main/ExamenFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Examen Final - Mineria

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [5]:
observados = np.array([3, 7, 5, 10])
predichos = np.array([2, 8, 4, 9])

In [7]:
errores = observados - predichos
errores_cuadrados = errores**2
suma_errores_cuadrados = np.sum(errores_cuadrados)

# CORRECCIÓN: Se divide entre len(observados), no se multiplica
mse = suma_errores_cuadrados / len(observados)

rmse = np.sqrt(mse)
print(rmse)

1.0

In [9]:
probablidad_a_d = 0.6 * 0.02
probablidad_b_d = 0.4 * 0.05

print(probablidad_a_d)
print(probablidad_b_d)

0.012
0.020000000000000004

In [10]:
probabilidad_defectuosa_total = probablidad_a_d + probablidad_b_d  # 0.032

# 2. Aplicar Bayes: (Casos favorables de B) / (Casos defectuosos totales)
bayes_b = probablidad_b_d / probabilidad_defectuosa_total

print(f"Probabilidad de que sea de la máquina B: {bayes_b:.3f}")

Probabilidad de que sea de la máquina B: 0.625

In [28]:
from google.colab import files
uploaded = files.upload()

Saving sensores.csv to sensores (1).csv

In [18]:
import pandas as pd
clientes = pd.read_csv('clientes.csv')
clientes #display the dataframe

   cliente_id  nombre  segmento
0           1     Ana   Premium
1           2    Luis  Standard
2           3  Camila  Standard
3           4    Jose   Premium

In [19]:
ordenes = pd.read_csv("ordenes.csv")
ordenes

   orden_id  cliente_id  monto
0       101           1    300
1       102           1    150
2       103           3    200
3       104           5    400

In [20]:
df= clientes.merge(ordenes, on="cliente_id",  how='left')
df.head()

   cliente_id  nombre  segmento  orden_id  monto
0           1     Ana   Premium     101.0  300.0
1           1     Ana   Premium     102.0  150.0
2           2    Luis  Standard       NaN    NaN
3           3  Camila  Standard     103.0  200.0
4           4    Jose   Premium       NaN    NaN

In [21]:
montos = df.groupby("nombre")["monto"].sum().fillna(0)
montos

nombre
Ana       450.0
Camila    200.0
Jose        0.0
Luis        0.0
Name: monto, dtype: float64

In [25]:
#3
df = pd.read_csv('items.csv')
df.eval('importe = precio * cantidad', inplace=True)
print(df)
dfa = df.query("categoria == 'A'")
promedios_por_categoria = df.groupby('categoria')['importe'].mean()
print(promedios_por_categoria)

promedio_A = promedios_por_categoria.loc['A']
print(f"\nEl promedio de la categoría A es: {promedio_A:.3f}")

  categoria item  precio  cantidad  importe
0         A    x     100         2      200
1         A    y     250         1      250
2         B    z      80         5      400
3         B    w     120         3      360
4         A    k     200         2      400
categoria
A    283.333333
B    380.000000
Name: importe, dtype: float64

El promedio de la categoría A es: 283.333

In [31]:
#Sensores
sensores = pd.read_csv('sensores.csv')
sensores

   id                   ts  temperatura  humedad ubicacion
0  a1     2025-02-01 10:00         23.5     45.2   almacen
1  a2     2025/02/01 10:05          NaN     46.0   almacen
2  a3     01-02-2025 10:10         22.1      NaN   oficina
3  a4  2025-02-01T10:15:00          NaN     47.3   oficina

In [32]:
df=sensores[["ts", "temperatura", "humedad"]]
df

                    ts  temperatura  humedad
0     2025-02-01 10:00         23.5     45.2
1     2025/02/01 10:05          NaN     46.0
2     01-02-2025 10:10         22.1      NaN
3  2025-02-01T10:15:00          NaN     47.3

In [34]:
df["ts"] = pd.to_datetime(df["ts"], format='mixed', errors='coerce')
df["temperatura"].fillna(df["temperatura"].median())

/tmp/ipykernel_1131/2218983674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ts"] = pd.to_datetime(df["ts"], format='mixed', errors='coerce')

0    23.5
1    22.8
2    22.1
3    22.8
Name: temperatura, dtype: float64

In [35]:
df["humedad"].fillna(df["humedad"].mean())

0    45.200000
1    46.000000
2    46.166667
3    47.300000
Name: humedad, dtype: float64

In [37]:
final_mediana_temp = df['temperatura'].median()
final_mediana_temp

22.8

In [38]:
#agua y cafe

Acontinuación se te presenta una simulación de un caso en el que se pretende determinar si el consumo de café por los estudiantes ayuda a estudiar.

Imagina que seleccionas a 20 estudiantes al azar. A 10 les das café y a otros 10 les das agua, luegos les pides que resuelvan un examen de lógica.

In [39]:
import pandas as pd
import numpy as np


# Establece una semilla para reproducibilidad
np.random.seed(42)


# 1. Crea una lista de matrículas de estudiantes
student_ids = [f'{i:06d}' for i in range(172120, 172120 + 20)]


# 2. Asigna 10 estudiantes al grupo 'Café' y 10 al grupo 'Agua'
groups = ['Café'] * 10 + ['Agua'] * 10
np.random.shuffle(groups)


# 3. Simula calificacionen de examenes para el grupo café
# Mean=70, Std=5, asegurate de que los valores estén entre (50-100)
coffee_scores = np.random.normal(loc=70, scale=5, size=10).round(0)
coffee_scores = np.clip(coffee_scores, 50, 100).astype(int)


# 4. Simula calificaciones de examen para el grupo de 'Agua'
# Mean=75, Std=5, asegurate de que los valores estén entre (50-100)
water_scores = np.random.normal(loc=75, scale=5, size=10).round(0)
water_scores = np.clip(water_scores, 50, 100).astype(int)


# Combina los valores basado en el grupo
exam_scores = []
coffee_idx = 0
water_idx = 0
for group in groups:
    if group == 'Café':
        exam_scores.append(coffee_scores[coffee_idx])
        coffee_idx += 1
    else:
        exam_scores.append(water_scores[water_idx])
        water_idx += 1


# 5. Combina en un DataFrame de Pandas
df_students = pd.DataFrame({
    'Matrícula': student_ids,
    'Grupo': groups,
    'Calificaciones': exam_scores
})


print("Datos simulados:")
print(df_students.head())

Datos simulados:
  Matrícula Grupo  Calificaciones
0    172120  Café              77
1    172121  Agua              77
2    172122  Agua              79
3    172123  Café              78
4    172124  Café              58

In [42]:
medianaC = df_students.query("Grupo == 'Café'").median(numeric_only=True)
medianaC

Calificaciones    71.0
dtype: float64

In [43]:
medianaA = df_students.query("Grupo == 'Agua'").median(numeric_only=True)
medianaA

Calificaciones    75.0
dtype: float64