<a href="https://colab.research.google.com/github/m-ony/mineria-de-datos/blob/main/Humano_o_IA%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#monica hernandez quiroz 181619

In [1]:
ia="""Es una herramienta que tiene la capacidad de pensar, actuar, razonar similar a un ser humano.
  La inteligencia artificial se puede usar para distintos ámbitos y ser entrenada para resolver problemas o ayudar a automatizar procesos o actividades diarias dentro de empresas, hogares, instituciones, etc."""

In [6]:
ia2="""La Inteligencia Artificial (IA) es un campo de la informática enfocado en el diseño y creación de sistemas, algoritmos y programas capaces de simular procesos cognitivos humanos. Su objetivo principal es permitir que las máquinas analicen datos, identifiquen patrones, razonen lógicamente, tomen decisiones autónomas y aprendan de sus propias experiencias para resolver problemas complejos, abarcando capacidades que van desde la percepción visual y la comprensión del lenguaje natural hasta la automatización adaptativa en diversos entornos."""

In [2]:
import os
import nltk
import random
import collections

In [53]:
nltk.download('punkt_tab')
nltk.download("stopwords")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [29]:
#Tokenizador
def tokenizar(libro):
    puntuacion = r'!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~¿¡—–'

    # Normalizar
    libro = libro.lower()

    # Tokenizar
    tokens = nltk.word_tokenize(libro, "spanish")

    # Quitar puntuación de los extremos
    for i, token in enumerate(tokens):
        tokens[i] = token.strip(puntuacion)

    # Volver a formar texto
    texto = " ".join(tokens)

    # Tokenizar nuevamente
    tokens = nltk.word_tokenize(libro, "spanish")

    # Quedarnos solamente con palabras
    tokens = [
        token for token in tokens
        if token.isalpha()]
    return tokens

In [54]:
#Stop Words
palabras_funcionales=nltk.corpus.stopwords.words("spanish")
print(palabras_funcionales)

['de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por', 'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual', 'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi', 'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros', 'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos', 'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros', 'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas', 'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'esté', 'estés', 'estemos', 'estéis', 'estén', 'estaré', 'estarás', 'estará', 'estaremos', 'estaréis', 'estarán', 'estaría', 'estarías', 'estaríamos', 'estaríais', 'estarían', 'estaba', 'estabas', 'estábamos', 'estabais', 'estaban', 'estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron', 'estuviera', 'estuvieras', 'estuviéramos', 'estuvierais', 'estuvieran', 'estuviese', 'estuvieses', 'estuviésemos', 'estuvieseis', 'estuviesen', 'estando', 'estado', 'estada', 'estados', 'estadas', 'estad', 'he', 'has', 'ha', 'hemos', 'habéis', 'han', 'haya', 'hayas', 'hayamos', 'hayáis', 'hayan', 'habré', 'habrás', 'habrá', 'habremos', 'habréis', 'habrán', 'habría', 'habrías', 'habríamos', 'habríais', 'habrían', 'había', 'habías', 'habíamos', 'habíais', 'habían', 'hube', 'hubiste', 'hubo', 'hubimos', 'hubisteis', 'hubieron', 'hubiera', 'hubieras', 'hubiéramos', 'hubierais', 'hubieran', 'hubiese', 'hubieses', 'hubiésemos', 'hubieseis', 'hubiesen', 'habiendo', 'habido', 'habida', 'habidos', 'habidas', 'soy', 'eres', 'es', 'somos', 'sois', 'son', 'sea', 'seas', 'seamos', 'seáis', 'sean', 'seré', 'serás', 'será', 'seremos', 'seréis', 'serán', 'sería', 'serías', 'seríamos', 'seríais', 'serían', 'era', 'eras', 'éramos', 'erais', 'eran', 'fui', 'fuiste', 'fue', 'fuimos', 'fuisteis', 'fueron', 'fuera', 'fueras', 'fuéramos', 'fuerais', 'fueran', 'fuese', 'fueses', 'fuésemos', 'fueseis', 'fuesen', 'sintiendo', 'sentido', 'sentida', 'sentidos', 'sentidas', 'siente', 'sentid', 'tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen', 'tenga', 'tengas', 'tengamos', 'tengáis', 'tengan', 'tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán', 'tendría', 'tendrías', 'tendríamos', 'tendríais', 'tendrían', 'tenía', 'tenías', 'teníamos', 'teníais', 'tenían', 'tuve', 'tuviste', 'tuvo', 'tuvimos', 'tuvisteis', 'tuvieron', 'tuviera', 'tuvieras', 'tuviéramos', 'tuvierais', 'tuvieran', 'tuviese', 'tuvieses', 'tuviésemos', 'tuvieseis', 'tuviesen', 'teniendo', 'tenido', 'tenida', 'tenidos', 'tenidas', 'tened']

In [55]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
#count vectorizer por que se nececita saber la cantidad de veces que se utilizan cada palabra
def frecuencia(texto):
  vectorizer = CountVectorizer(tokenizer=tokenizar, stop_words= palabras_funcionales)
  X = vectorizer.fit_transform(texto)
  vocabulario = vectorizer.get_feature_names_out()
  print(X.shape)

  indice = ["texto"]
  tabla_frecuencias= pd.DataFrame(X.toarray(), index=indice, columns=vocabulario)
  return tabla_frecuencias

In [57]:
#Primer texto hecho por humano
tabla1 = frecuencia([ia])
tabla1

(1, 27)

/usr/local/lib/python3.13/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,actividades,actuar,artificial,automatizar,ayudar,capacidad,dentro,diarias,distintos,empresas,...,pensar,problemas,procesos,puede,razonar,resolver,ser,similar,usar,ámbitos
texto,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,2,1,1,1

In [58]:
#ordenar de mayor a menor
tabla_ordenada_1=tabla1.sort_values(by="texto", axis=1, ascending=False)
tabla_ordenada_1

,ser,actuar,actividades,automatizar,ayudar,capacidad,dentro,diarias,distintos,empresas,...,pensar,humano,problemas,procesos,razonar,puede,resolver,similar,usar,ámbitos
texto,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [59]:
#5 plabras mas usadas
top_5 = tabla_ordenada_1.iloc[:, :5]
top_5

       ser  actuar  actividades  automatizar  ayudar
texto    2       1            1            1       1

In [61]:
#Segundo texto hecho por IA
tabla2=frecuencia([ia2])
tabla2

(1, 47)

/usr/local/lib/python3.13/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,abarcando,adaptativa,algoritmos,analicen,aprendan,artificial,automatización,autónomas,campo,capaces,...,procesos,programas,propias,razonen,resolver,simular,sistemas,tomen,van,visual
texto,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [62]:
#ordenar de mayor a menor
tabla_ordenada_2=tabla2.sort_values(by="texto", axis=1, ascending=False)
tabla_ordenada_2

,abarcando,adaptativa,algoritmos,analicen,aprendan,artificial,automatización,autónomas,campo,capaces,...,procesos,programas,propias,razonen,resolver,simular,sistemas,tomen,van,visual
texto,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [63]:
#5 plabras mas usadas
top_5 = tabla_ordenada_2.iloc[:, :5]
top_5

       abarcando  adaptativa  algoritmos  analicen  aprendan
texto          1           1           1         1         1

podemos dieferenciar quién escribió cada definición.

Se puede llegar a diferenciar un poco ya que hay plabras mas tecnicas a las que un humano o estudiante puede llegar a usar, un humano utiliza palanbras mas simpkles no tan tecnicas.